# Generated by Django 3.0.11 on 2020-11-29 14:45

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20201129_1408'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, upload_to='about_pics')),
            ],
        ),
        migrations.AlterField(
            model_name='homepost',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 29, 14, 45, 20, 518718, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='homepost',
            name='image',
            field=models.ImageField(blank=True, upload_to='home_pics'),
        ),
        migrations.AlterField(
            model_name='order',
            name='date_ordered',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 29, 14, 45, 20, 519104, tzinfo=utc)),
        ),
    ]
