# Generated by Django 3.0.11 on 2020-11-29 15:12

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20201129_1457'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='instructions',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='homepost',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 29, 15, 12, 42, 702121, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='order',
            name='date_ordered',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 29, 15, 12, 42, 702505, tzinfo=utc)),
        ),
    ]
