# Generated by Django 3.0.11 on 2020-11-29 18:40

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_auto_20201129_1748'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('placed', 'Placed'), ('processed', 'Processed'), ('shipped', 'Shipped')], default='placed', max_length=9),
        ),
        migrations.AlterField(
            model_name='homepost',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 29, 18, 40, 21, 5172, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='order',
            name='date_ordered',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 29, 18, 40, 21, 5735, tzinfo=utc)),
        ),
    ]
