# Generated by Django 3.0.11 on 2020-12-02 13:34

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_auto_20201202_1333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepost',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 2, 13, 34, 25, 416009, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='order',
            name='date_ordered',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 2, 13, 34, 25, 416404, tzinfo=utc)),
        ),
    ]
