# Generated by Django 3.0.11 on 2020-12-02 15:40

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_auto_20201202_1334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutpost',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='about_pics'),
        ),
        migrations.AlterField(
            model_name='homepost',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 2, 15, 40, 18, 551977, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='homepost',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='home_pics'),
        ),
        migrations.AlterField(
            model_name='order',
            name='date_ordered',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 2, 15, 40, 18, 552364, tzinfo=utc)),
        ),
    ]
